<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text"
            doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
            version="4.01"
            indent="yes" />

	<xsl:param name="prolog"/>
	<xsl:param name="epilog"/>

	<xsl:template match="/">
		<xsl:if test="$prolog = 'true'">
			<xsl:call-template name="head"/>
		</xsl:if>
		<xsl:apply-templates/>
		<xsl:if test="$epilog = 'true'">
			<xsl:call-template name="foot"/>
		</xsl:if>
	</xsl:template>
	
	
	<xsl:template name="head">
		&lt;html&gt;
		&lt;head&gt;
			&lt;meta http-equiv="content-type" content="text/html; charset="UTF-8"&gt;
			&lt;title&gt; generated by Liabolo HTML Export &lt;/title&gt;
		&lt;/head&gt;
		&lt;body&gt;
	</xsl:template>
	
	<xsl:template name="foot">
		&lt;/ul&gt;
		&lt;/body&gt;
		&lt;/html&gt;
		&lt;ul&gt;
	</xsl:template>
	
    <!-- Hier das csv-Format-->
    <xsl:template name="csvOutput" match="mediatype">
        &lt;li&gt;
        <xsl:for-each select="creator"><xsl:value-of select="."/>,</xsl:for-each>
        <xsl:for-each select="title"><xsl:value-of select="."/>,</xsl:for-each>
        <!-- <xsl:for-each select="subject"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="description"><xsl:value-of select="."/>,</xsl:for-each> -->
        <xsl:for-each select="publisher"><xsl:value-of select="."/>,</xsl:for-each>
        <!-- <xsl:for-each select="contributers"><xsl:value-of select="."/>,</xsl:for-each> -->
        <xsl:for-each select="date"><xsl:value-of select="."/>,</xsl:for-each>
        <!-- <xsl:for-each select="type"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="format"><xsl:value-of select="."/>,</xsl:for-each> -->
        <xsl:for-each select="identifier"><xsl:value-of select="."/>,</xsl:for-each>
        <xsl:for-each select="source"><xsl:value-of select="."/>,</xsl:for-each>
        <!-- <xsl:for-each select="language"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="relation"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="coverage"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="rights"><xsl:value-of select="."/>,</xsl:for-each> -->
        <!-- <xsl:for-each select="branch"><xsl:value-of select="."/>,</xsl:for-each> -->
        <xsl:for-each select="signature"><xsl:value-of select="."/></xsl:for-each>
        &lt;/li&gt;
    </xsl:template>
</xsl:stylesheet>
